apiVersion: novus.legogroup.io/v1alpha1
kind: WebApp
metadata:
  name: first-app
spec:
  ingress:
    subdomain: first-app
  service:
    image:
      # NOTICE: Update this line to point to your repo
      repository: ghcr.io/dtu-platform-workshop/dtu-<your-github-username>/first-app 
      # NOTICE: Update this line to whatever tag you see when you find it 
      # under the "Packages" in your repository 
      tag: 20260919-6cf019c

    useSamePortForHealthProbes: true

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
